[build]
  command = "npm run build"
  functions = "functions"
  publish = "public"
# [[plugins]]
#    package = "netlify-plugin-a11y"

#   # all inputs are optional, we just show you the defaults below
#   [plugins.inputs]
  
#   # required config
#   #checkPaths = ['/'] # you can give an array of directories or paths to html files, that you want to run a11y checks on

#   ## Another checkPaths Example 
#   checkPaths = [
#     '/contactus',
#   ]
  
#   # # optional config
#   # resultMode = "warn" # is "error" by default

#   # # Developer only
#   debugMode = true # extra logging for plugin developers